
#
#echo show databases | mysql -uroot -p"${MYSQL_PASSWORD}" &>>${LOG}
#if [ $? -ne 0 ]; then
#PRINT "RESET Root Password"
#echo "ALTER USER 'root'@'localhost' IDENTIFIED BY '${MYSQL_PASSWORD}';" | mysql --connect-expired-password -uroot -p"${MYSQL_DEFAULT_PASSWORD}" &>>${LOG}
#CHECK_STAT $?
#fi
#
#echo show plugins  | mysql -uroot -p"${MYSQL_PASSWORD}" 2>>${LOG} | grep validate_password &>>${LOG}
#if [ $? -eq 0 ]; then
#PRINT "Uninstall Password Validate Plugin"
#echo "uninstall plugin validate_password;" | mysql -uroot -p"${MYSQL_PASSWORD}" &>>${LOG}
#CHECK_STAT $?
#fi
#
#
#PRINT "Download Schema"
#curl -s -L -o /tmp/mysql.zip "https://github.com/roboshop-devops-project/mysql/archive/main.zip" &>>${LOG}
#CHECK_STAT $?
#
#PRINT "Load Schema"
#cd /tmp && unzip -o mysql.zip &>>${LOG} && cd mysql-main && mysql -u root -p"${MYSQL_PASSWORD}" <shipping.sql &>>${LOG}
#CHECK_STAT $?
#
- name: Fail if the Password MYSQL_PASSWORD does not exist
  ansible.builtin.fail:
    msg: MYSQL_PASSWORD variable is missing.
  when: MYSQL_PASSWORD is undefined

- name: Copy MySQL Repo File
  ansible.builtin.template:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Install MySQL Server
  ansible.builtin.yum:
    name:
      - mysql-community-server
      - MySQL-python
    state: installed

- name: Start MySQL Service
  ansible.builtin.systemd:
    name: mysqld
    state: started
    enabled: yes

- name: Fetch MySQL Log File
  ansible.builtin.slurp:
    src: /var/log/mysqld.log
  register: mysql_log

- name: Fetch Password from MySQL LOG File
  ansible.builtin.set_fact:
    DEFAULT_PASSWORD: "{{mysql_log['content'] | b64decode | regex_findall('.*temporary password.*') | join(' ')| split(' ') | last}}"

- name: Check MySQL Password has been reset or not
  community.mysql.mysql_info:
    login_user: root
    login_password: "{{MYSQL_PASSWORD}}"
    filter: version





