- name: Remove App Code
  ansible.builtin.file:
    path: "{{ APP_LOCATION }}"
    state: absent

- name: Download & Extract {{ COMPONENT }} Component Archive
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/{{ COMPONENT }}/archive/main.zip
    dest: /tmp
    remote_src: yes

