- name: Install Maven
  ansible.builtin.yum:
    name: maven
    state: installed

- name: Import Common App Setup Configurations
  ansible.builtin.include_role:
    name: common
    tasks_from: download

- name: Install Maven Dependencies
  ansible.builtin.shell: mvn clean package && mv target/{{COMPONENT}}-1.0.jar {{COMPONENT}}.jar
  args:
    chdir: /home/roboshop/{{COMPONENT}}

- name: SystemD Setup for {{ COMPONENT }} Service
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd

