- name: Setup {{ COMPONENT }} SystemD Service
  ansible.builtin.template:
    src: systemd.service
    dest: /etc/systemd/system/{{ COMPONENT }}.service

- name: Start {{ COMPONENT }} Service
  ansible.builtin.systemd:
    name: "{{ COMPONENT }}"
    enabled: yes
    state: restarted
    daemon_reload: yes
